### ISSUE TITLE
Backend Milestones Setup, documentation for backend-app & API services available

### ISSUE THREAD

**Issue by modelomaker812** [MoonBaseDAO/backend-app#3]
Backend Team:
---

@christiankesslers @modelomaker812 

***
**Priority: ==1==** 
- [ ] 1. [Resolving Issue #1](https://github.com/MoonBaseDAO/backend-app/issues/1) 

**Estimated Timeframe: 3-6 Hours**
***

**Priority: ==2==**
- [ ] 2. Develop API's for CRUD operations.
    - API for business logic 
        + - [ ] [store user id/data] 
        + - [ ] [accept/process requests] 
        + - [ ] [error reporting] 

**Estimated Timeframe: 1-3 Hours**
***

**Priority: ==3==** 
- [ ] 3. Implement the necessary business logic to handle the CRUD operations.
    - Implement/Test
        + - [ ] [code logic into backend app to follow CRUD operations]
        + - [ ] [write tests & document CRUD operations in backend app]

**Estimated Timeframe: 1-3 Hours**
***

**Priority: ==4==** 
- [ ] 4. Store the customer data in a database and ensure that it is properly secured.
    - Implement/Test MongoDB CRUD Operations & Data Integrity Checks
        + - [ ] [backend app utilizes mongodb to store user auth & client session info]
        + - [ ] [mongodb is safely sync'd & backed up regularly]

**Estimated Timeframe: 1-3 Hours**
***

**Priority: ==5==**
- [ ] 5. Respond to API calls from the frontend and return the appropriate results.
    - Frontend & Backend Implement/Test
        + - [ ] [Frontend makes API call to backend app]
        + - [ ] [Backend app receives API call from frontend and responds to the request with results.]

**Estimated Timeframe: 1-3 Hours**
***
